version: '3'
services:
    postgres:
        image: 'postgres:9.6'
        container_name: db
        restart: always
        environment:
            - POSTGRES_PASSWORD=password
        volumes:
            - ./db-init:/docker-entrypoint-initdb.d